# Generated by Django 3.2 on 2021-05-07 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_last', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backdrop_path', models.CharField(blank=True, max_length=255)),
                ('imbd_id', models.CharField(blank=True, max_length=255)),
                ('tmdb_id', models.IntegerField()),
                ('original_language', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateField()),
                ('runtime', models.IntegerField()),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('vote_average', models.FloatField(blank=True)),
                ('vote_count', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_last', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(to='movieswyper.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='UserMovieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_last', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieswyper.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_genres', models.ManyToManyField(to='movieswyper.Genre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_path', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('origin_country', models.CharField(blank=True, max_length=255)),
                ('movies_produced', models.ManyToManyField(to='movieswyper.Movie')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usermovierating',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_rating'),
        ),
    ]
