# Generated by Django 3.2 on 2021-05-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieswyper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='tmdb_id',
            field=models.IntegerField(db_index=True, default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
