# Generated by Django 3.2 on 2021-05-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieswyper', '0002_auto_20210507_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncompany',
            name='tmdb_id',
            field=models.IntegerField(db_index=True, default=0, unique=True),
            preserve_default=False,
        ),
    ]
